<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f403ebdd-1e37-4233-b476-fa87f3243a62</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\images\books\1.png" />
    <Content Remove="wwwroot\images\books\10.png" />
    <Content Remove="wwwroot\images\books\11.png" />
    <Content Remove="wwwroot\images\books\12.png" />
    <Content Remove="wwwroot\images\books\2.png" />
    <Content Remove="wwwroot\images\books\3.png" />
    <Content Remove="wwwroot\images\books\4.png" />
    <Content Remove="wwwroot\images\books\5.png" />
    <Content Remove="wwwroot\images\books\6.png" />
    <Content Remove="wwwroot\images\books\7.png" />
    <Content Remove="wwwroot\images\books\8.png" />
    <Content Remove="wwwroot\images\books\9.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\images\books\1.png" />
    <EmbeddedResource Include="wwwroot\images\books\2.png" />
    <EmbeddedResource Include="wwwroot\images\books\3.png" />
    <EmbeddedResource Include="wwwroot\images\books\4.png" />
    <EmbeddedResource Include="wwwroot\images\books\5.png" />
    <EmbeddedResource Include="wwwroot\images\books\6.png" />
    <EmbeddedResource Include="wwwroot\images\books\7.png" />
    <EmbeddedResource Include="wwwroot\images\books\8.png" />
    <EmbeddedResource Include="wwwroot\images\books\9.png" />
    <EmbeddedResource Include="wwwroot\images\books\10.png" />
    <EmbeddedResource Include="wwwroot\images\books\11.png" />
    <EmbeddedResource Include="wwwroot\images\books\12.png" />
  </ItemGroup>

  <ItemGroup>
  <Content Include="Database\seedAssets\books\**\book.pdf">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eKnjiga.Model\eKnjiga.Model.csproj" />
    <ProjectReference Include="..\eKnjiga.Services\eKnjiga.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\users\" />
  </ItemGroup>


</Project>
