version: '3'
services:
  eknjiga-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - eknjiga

  eknjiga-rabbit:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - eknjiga

  eknjiga-mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - eknjiga

  eknjiga-api:
    restart: unless-stopped
    build:
      context: .
      target: webapi
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7114:80
    volumes:
      - ./eKnjiga.WebAPI/wwwroot:/app/wwwroot
    networks:
      - eknjiga
    depends_on:
      - eknjiga-sql
      - eknjiga-rabbit

  eknjiga-worker:
    restart: unless-stopped
    build:
      context: .
      target: worker
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - eknjiga
    depends_on:
      - eknjiga-sql
      - eknjiga-rabbit

networks:
  eknjiga:
    driver: bridge
